#
# Module manifest for module 'DreamChecker'
#
# Generated by: Igor Spichkin
#
# Generated on: 26.05.2021
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''

    # Version number of this module.
    ModuleVersion   = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID            = '0736bd8f-7958-4430-80ad-baaa4823034c'

    # Author of this module
    Author          = 'Igor Spichkin'

    # Company or vendor of this module
    CompanyName     = 'ChaoticOnyx'

    # Copyright statement for this module
    Copyright       = '(c) ChaoticOnyx. All rights reserved.'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(
        'GitHub'
    )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules   = @(
        'DreamChecker.ps1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData     = @{

        PSData = @{
        }

    }
}

