#
# Module manifest for module 'CodeStyle'
#
# Generated by: Igor Spichkin
#
# Generated on: 26.05.2021
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID          = '701a63f0-ff17-44bd-b9d1-a74eaa49de22'

    # Author of this module
    Author        = 'Igor Spichkin'

    # Company or vendor of this module
    CompanyName   = 'ChaoticOnyx'

    # Copyright statement for this module
    Copyright     = '(c) ChaoticOnyx. All rights reserved.'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        'CodeStyle.ps1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData   = @{

        PSData = @{
        }

    }
}
