var/list/combatlog = list()
var/list/IClog     = list()
var/list/OOClog    = list()
var/list/adminlog  = list()

GLOBAL_REAL(config,    /datum/configuration)
GLOBAL_REAL(watchlist, /datum/watchlist)

var/list/jobMax        = list()

GLOBAL_VAR(log_directory)
GLOBAL_PROTECT(log_directory)

GLOBAL_VAR(world_runtime_log)
GLOBAL_PROTECT(world_runtime_log)
GLOBAL_VAR(world_qdel_log)
GLOBAL_PROTECT(world_qdel_log)
GLOBAL_VAR(world_debug_log)
GLOBAL_PROTECT(world_debug_log)
GLOBAL_VAR(world_hrefs_log)
GLOBAL_PROTECT(world_hrefs_log)
GLOBAL_VAR(href_exploit_attempt_log)
GLOBAL_PROTECT(href_exploit_attempt_log)
GLOBAL_VAR(world_common_log)
GLOBAL_PROTECT(world_common_log)
GLOBAL_VAR(tgui_log)
GLOBAL_PROTECT(tgui_log)
GLOBAL_VAR(world_demo_log)
GLOBAL_PROTECT(world_demo_log)
