export type AvailableJob = keyof typeof JOB2ICON;

/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2ICON = {
  AI: "eye",
  Assistant: "toolbox",
  "Technical Assistant": "toolbox",
  "Research Assistant": "toolbox",
  "Medical Intern": "toolbox",
  "Atmospheric Technician": "fan",
  Bartender: "cocktail",
  Gardener: "seedling",
  Hydroponicist: "seedling",
  Captain: "crown",
  "Cargo Technician": "dolly",
  Chaplain: "cross",
  Counselor: "cross",
  Chef: "utensils",
  Cook: "utensils",
  Chemist: "flask",
  Pharmacist: "flask",
  "Chief Engineer": "screwdriver-wrench",
  "Chief Medical Officer": "user-md",
  Clown: "face-grin-tears",
  Cyborg: "robot",
  Android: "robot",
  Detective: "user-secret",
  "Forensic Technician": "user-secret",
  "Head of Personnel": "dog",
  "Head of Security": "user-shield",
  Janitor: "dumpster",
  Custodian: "dumpster",
  "Sanitation Technicial": "dumpster",
  Lawyer: "gavel",
  Librarian: "book-open",
  "Medical Doctor": "stethoscope",
  Surgeon: "stethoscope",
  "Emergency Physician": "stethoscope",
  Nurse: "stethoscope",
  Mime: "comment-slash",
  Merchant: "dollar-sign",
  Paramedic: "truck-medical",
  "Emergency Medical Technician": "truck-medical",
  "Personal AI": "mobile-alt",
  Prisoner: "lock",
  Psychiatrist: "brain",
  Psychologist: "brain",
  "Internal Affairs Agent": "briefcase",
  Quartermaster: "sack-dollar",
  "Research Director": "user-graduate",
  Roboticist: "battery-half",
  "Biomechanical Engineer": "battery-half",
  "Mechatronic Engineer": "battery-half",
  Scientist: "atom",
  Xenoarcheologist: "atom",
  Anomalist: "atom",
  "Plasma Researcher": "atom",
  "Security Officer": "shield-halved",
  "Junior Officer": "shield-halved",
  "Shaft Miner": "digging",
  "Drill Technician": "digging",
  Prospector: "digging",
  "Station Engineer": "gears",
  "Maintenance Technician": "gears",
  "Engine Technician": "gears",
  Electrician: "gears",
  "Syndicate Operative": "dragon",
  Virologist: "virus",
  Warden: "handcuffs",
  Waiter: "wine-glass-empty",
  Xenobiologist: "dna",
  Xenobotanist: "dna",
} as const;
