/obj/secure_closet/medical1/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/gl_kit( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/antitoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/inaprovaline( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/stoxin( src )
	new /obj/item/weapon/reagent_containers/glass/bottle/toxin( src )
	new /obj/item/weapon/storage/firstaid/syringes( src )
	new /obj/item/weapon/storage/pill_bottle/kelotane( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/dropper( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	new /obj/item/weapon/reagent_containers/glass/beaker( src )
	return
/obj/secure_closet/medical3/New()
	..()
	sleep(2)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/A(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/B(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/O(src)
	new/obj/item/weapon/reagent_containers/glass/bloodpack/AB(src)
/obj/secure_closet/medical2/New()
	..()
	sleep(2)
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/weapon/tank/anesthetic( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	new /obj/item/clothing/mask/medical( src )
	return
