#define EMOTE_CHECK_CONSCIOUS           			0x1
#define EMOTE_CHECK_ONE_HAND_USABLE     			0x2
#define EMOTE_CHECK_IS_HEAD_PRESENT     			0x4
#define EMOTE_CHECK_IS_SYNTH_OR_ROBOT   			0x8
#define EMOTE_CHECK_ROBOT_SEC_MODULE    			0x10
#define EMOTE_CHECK_CONSCIOUS_OR_NOT_INTENTIONAL	0x20
