#define BLOBCORECOSTINC 50
#define BLOBCOREBASECOST 100
#define BLOBSHICOST 10
#define BLOBRESCOST 30
#define BLOBFACCOST 45
#define BLOBNODCOST 20
#define BLOBATTCOST 15
#define BLOBRALCOST 5
#define BLOBTAUNTCOST 15
#define BLOBNDPOINTINC 10

#define BLOBCORECD 20 SECONDS
#define BLOBSHICD 2 SECONDS
#define BLOBRESCD 10 SECONDS
#define BLOBFACCD 10 SECONDS
#define BLOBNODCD 10 SECONDS
#define BLOBATTCD 2 SECOND
#define BLOBTAUNTCD 5 SECONDS
