#define BORER_STATUS_IN_HOST BORER_STATUS_IN_HOST
#define BORER_STATUS_CONTROLLING "controlling"
#define BORER_STATUS_NOT_CONTROLLING "not_controlling"
#define BORER_STATUS_OUT_HOST "out_host"
#define BORER_STATUS_HUSK "husk"
