// BYOND lower-cases color values, and thus we do so as well to ensure atom.color == COLOR_X will work correctly
#define COLOR_DARKMODE_BACKGROUND "#202020"
#define COLOR_DARKMODE_DARKBACKGROUND "#171717"
#define COLOR_DARKMODE_TEXT "#a4bad6"

#define COLOR_MARINEMODE_DARKBACKGROUND "#1e1e1e"
#define COLOR_MARINEMODE_BACKGROUND "#2e332b"
#define COLOR_MARINEMODE_TEXT "#a4bad6"
#define COLOR_MARINEMODE_GRAYBUTTON "#626f5b"
#define COLOR_MARINEMODE_DARKGRAYBUTTON "#3a3a3a"

#define COLOR_BLACK            "#000000"
#define COLOR_NAVY_BLUE        "#000080"
#define COLOR_GREEN            "#008000"
#define COLOR_DARK_GRAY        "#404040"
#define COLOR_MAROON           "#800000"
#define COLOR_PURPLE           "#800080"
#define COLOR_VIOLET           "#9933ff"
#define COLOR_OLIVE            "#808000"
#define COLOR_BROWN_ORANGE     "#824b28"
#define COLOR_DARK_ORANGE      "#b95a00"
#define COLOR_GRAY40           "#666666"
#define COLOR_SEDONA           "#cc6600"
#define COLOR_DARK_BROWN       "#917448"
#define COLOR_BLUE             "#0000ff"
#define COLOR_DEEP_SKY_BLUE    "#00e1ff"
#define COLOR_LIME             "#00ff00"
#define COLOR_CYAN             "#00ffff"
#define COLOR_TEAL             "#33cccc"
#define COLOR_RED              "#ff0000"
#define COLOR_PINK             "#ff00ff"
#define COLOR_ORANGE           "#ff9900"
#define COLOR_YELLOW           "#ffff00"
#define COLOR_GRAY             "#808080"
#define COLOR_RED_GRAY         "#aa5f61"
#define COLOR_BROWN            "#b19664"
#define COLOR_DARK_BROWN_NEW   "#512B0F"
#define COLOR_GREEN_GRAY       "#8daf6a"
#define COLOR_BLUE_GRAY        "#6a97b0"
#define COLOR_SUN              "#ec8b2f"
#define COLOR_PURPLE_GRAY      "#a2819e"
#define COLOR_BLUE_LIGHT       "#33ccff"
#define COLOR_RED_LIGHT        "#ff3333"
#define COLOR_BEIGE            "#ceb689"
#define COLOR_PALE_GREEN_GRAY  "#aed18b"
#define COLOR_PALE_RED_GRAY    "#cc9090"
#define COLOR_PALE_PURPLE_GRAY "#bda2ba"
#define COLOR_PALE_BLUE_GRAY   "#8bbbd5"
#define COLOR_LUMINOL          "#66ffff"
#define COLOR_SILVER           "#c0c0c0"
#define COLOR_GRAY80           "#cccccc"
#define COLOR_OFF_WHITE        "#eeeeee"
#define COLOR_WHITE            "#ffffff"
#define COLOR_NT_RED           "#9d2300"
#define COLOR_GUNMETAL         "#80868e"
#define COLOR_MUZZLE_FLASH     "#ffffb2"
#define COLOR_CHESTNUT         "#996633"
#define COLOR_BEASTY_BROWN     "#663300"
#define COLOR_WHEAT            "#ffff99"
#define COLOR_CYAN_BLUE        "#3366cc"
#define COLOR_LIGHT_CYAN       "#66ccff"
#define COLOR_PAKISTAN_GREEN   "#006600"

//Color defines used by the assembly detailer.

#define COLOR_ASSEMBLY_BLACK   "#545454"
#define COLOR_FLOORTILE_GRAY   "#8D8B8B"
#define COLOR_ASSEMBLY_BGRAY   "#9497ab"
#define COLOR_ASSEMBLY_WHITE   "#e2e2e2"
#define COLOR_ASSEMBLY_RED     "#cc4242"
#define COLOR_ASSEMBLY_ORANGE  "#e39751"
#define COLOR_ASSEMBLY_BEIGE   "#af9366"
#define COLOR_ASSEMBLY_BROWN   "#97670e"
#define COLOR_ASSEMBLY_GOLD    "#aa9100"
#define COLOR_ASSEMBLY_YELLOW  "#ceca2b"
#define COLOR_ASSEMBLY_GURKHA  "#999875"
#define COLOR_ASSEMBLY_LGREEN  "#789876"
#define COLOR_ASSEMBLY_GREEN   "#44843c"
#define COLOR_ASSEMBLY_LBLUE   "#5d99be"
#define COLOR_ASSEMBLY_BLUE    "#38559e"
#define COLOR_ASSEMBLY_PURPLE  "#6f6192"

//Color defines used by pipes.

#define	PIPE_COLOR_GREY        "#ffffff"	//yes white is grey
#define	PIPE_COLOR_RED         "#ff0000"
#define	PIPE_COLOR_BLUE        "#0000ff"
#define	PIPE_COLOR_CYAN        "#00ffff"
#define	PIPE_COLOR_GREEN       "#00ff00"
#define	PIPE_COLOR_YELLOW      "#ffcc00"
#define	PIPE_COLOR_BLACK       "#444444"
#define	PIPE_COLOR_ORANGE      "#b95a00"

#define COLOR_BLOOD_HUMAN "#a10808"
