// defines for contract type of impact to station
#define CONTRACT_DIFFICULTY_NONE    0
#define CONTRACT_DIFFICULTY_EASY    1
#define CONTRACT_DIFFICULTY_MEDIUM  2
#define CONTRACT_DIFFICULTY_HARD    3
#define CONTRACT_DIFFICULTY_EXTREME 4

// defines for steal contract
#define CONTRACT_STEAL_MILITARY   1
#define CONTRACT_STEAL_OPERATION  2
#define CONTRACT_STEAL_SCIENCE    3
#define CONTRACT_STEAL_UNDERPANTS 4
