
#define PATREON_NONE      0
#define PATREON_CARGO     1
#define PATREON_ENGINEER  2
#define PATREON_SCIENTIST 3
#define PATREON_HOS       4
#define PATREON_CAPTAIN   5
#define PATREON_WIZARD    6
#define PATREON_CULTIST   7
#define PATREON_ASSISTANT 8

#define PATREON_ALL_TIERS list(\
	PATREON_NONE, PATREON_CARGO, PATREON_ENGINEER, \
	PATREON_SCIENTIST, PATREON_HOS, PATREON_CAPTAIN, \
	PATREON_WIZARD, PATREON_CULTIST, PATREON_ASSISTANT)

#define DONATIONS_TRANSACTION_TYPE_PURCHASE "donation_store_purchase"
