
#define PATREON_NONE      "none"
#define PATREON_CARGO     "cargo"
#define PATREON_ENGINEER  "engineer"
#define PATREON_SCIENTIST "scientist"
#define PATREON_HOS       "hos"
#define PATREON_CAPTAIN   "captain"
#define PATREON_WIZARD    "wizard"
#define PATREON_CULTIST   "cultist"
#define PATREON_ASSISTANT "assistant"

#define PATREON_SCIENTIST_DISCOUNT 5
#define PATREON_HOS_DISCOUNT 9
#define PATREON_CAPTAIN_DISCOUNT 10
#define PATREON_WIZARD_DISCOUNT 15
#define PATREON_CULTIST_DISCOUNT 20
#define PATREON_ASSISTANT_DISCOUNT 100

#define PATREON_ALL_TIERS list(\
	PATREON_NONE, PATREON_CARGO, PATREON_ENGINEER, \
	PATREON_SCIENTIST, PATREON_HOS, PATREON_CAPTAIN, \
	PATREON_WIZARD, PATREON_CULTIST, PATREON_ASSISTANT)

#define DONATIONS_TRANSACTION_TYPE_PURCHASE "donation_store_purchase"
