#define STOMACH_EFFECT_WARNING             SPAN_WARNING("Your stomach feels heavy.")
#define ITCH_EFFECT_WARNING(X)             SPAN_WARNING("Your [X] itches like hell.")
#define GUNCK_EFFECT_WARNING               SPAN_WARNING("Mucous runs down the back of your throat.")
#define SNEEZE_EFFECT_WARNING              SPAN_WARNING("You feel like you are about to sneeze!")
#define DISORIENTATION_EFFECT_WARNING      SPAN_WARNING("You feel disoriented...")
#define STIMULANT_EFFECT_WARNING           SPAN_NOTICE("You feel a rush of energy inside you!")
#define HAIR_EFFECT_WARNING                SPAN_DANGER("Your hair starts to fall out in clumps...")
#define CONFUSION_EFFECT_WARNING           SPAN_NOTICE("You have trouble telling right and left apart all of a sudden.")
#define IMMORTAL_RECOVER_EFFECT_WARNING(X) SPAN_NOTICE("Your [X] suddenly feels much better!")
#define IMMORTAL_HEALING_EFFECT_WARNING(X) SPAN_NOTICE("Your [X] feels a bit warm...")
#define IMMORTAL_AGING_EFFECT_WARNING      SPAN_NOTICE("You suddenly feel hurt and old...")
#define ORGANS_SHUTDOWN_EFFECT_WARNING(X)  SPAN_NOTICE("You can't feel your [X] anymore...")
#define GIBBINGTONS_EFFECT_WARNING(X)      SPAN_WARNING("Your [X] feels as if it might burst!")
