#undef SURGERY_FAILURE
#undef SURGERY_BLOCKED

#undef SURGERY_DURATION_DELTA

#undef CUT_DURATION
#undef CLAMP_DURATION
#undef RETRACT_DURATION
#undef CAUTERIZE_DURATION
#undef GLUE_BONE_DURATION
#undef BONE_MEND_DURATION
#undef SAW_DURATION
#undef DRILL_DURATION
#undef ATTACH_DURATION
#undef ORGAN_FIX_DURATION
#undef CONNECT_DURATION
