#undef SURGERY_FAILURE
#undef SURGERY_BLOCKED

#undef CUT_MIN_DURATION
#undef CUT_MAX_DURATION

#undef CLAMP_MIN_DURATION
#undef CLAMP_MAX_DURATION

#undef RETRACT_MIN_DURATION
#undef RETRACT_MAX_DURATION

#undef CAUTERIZE_MIN_DURATION
#undef CAUTERIZE_MAX_DURATION

#undef GLUE_BONE_MIN_DURATION
#undef GLUE_BONE_MAX_DURATION

#undef BONE_MEND_MIN_DURATION
#undef BONE_MEND_MAX_DURATION

#undef SAW_MIN_DURATION
#undef SAW_MAX_DURATION

#undef DRILL_MIN_DURATION
#undef DRILL_MAX_DURATION

#undef ATTACH_MIN_DURATION
#undef ATTACH_MAX_DURATION

#undef ORGAN_FIX_MIN_DURATION
#undef ORGAN_FIX_MAX_DURATION

#undef CONNECT_MIN_DURATION
#undef CONNECT_MAX_DURATION
