/obj/closet/syndicate/nuclear/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/handcuff_kit( src )
	new /obj/item/weapon/storage/flashbang_kit( src )
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/weapon/gun/energy/general( src )
	new /obj/item/weapon/pinpointer( src )
	new /obj/item/weapon/pinpointer( src )
	new /obj/item/weapon/pinpointer( src )
	new /obj/item/device/pda/syndicate( src )
	new /obj/item/device/uplink/radio( src )
	return
