#
# Module manifest for module 'GitHub'
#
# Generated by: Igor Spichkin
#
# Generated on: 26.05.2021
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'GitHub.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # ID used to uniquely identify this module
    GUID              = '9db82761-a71b-4637-b4c8-70b7534328bd'

    # Author of this module
    Author            = 'Igor Spcichkin'

    # Company or vendor of this module
    CompanyName       = 'ChaoticOnyx'

    # Copyright statement for this module
    Copyright         = '(c) ChaoticOnyx. All rights reserved.'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules     = @(
        'GitHub.ps1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
        }
    }
}
