/// List of pipes. Fuck the guy who coded them.
GLOBAL_LIST_INIT(pipe_dispenser_recipes, list(
	"Regular pipes" = list(
		"Pipe" = 0,
		"Bent Pipe" = 1,
		"Manifold" = 5,
		"Manual Valve" = 8,
		"Digital Valve" = 9,
		"Automatic Shutoff Valve" = 44,
		"Pipe Cap" = 20,
		"4-Way Manifold" = 19,
		"Manual T-Valve" = 18,
		"Manual T-Valve - Mirrored" = 43,
		"Upward Pipe" = 21,
		"Downward Pipe" = 22,
	),
	"Supply pipes" = list(
		"Pipe" = 29,
		"Bent Pipe" = 30,
		"Manifold" = 33,
		"Pipe Cap" = 41,
		"4-Way Manifold" = 35,
		"Upward Pipe" = 37,
		"Downward Pipe" = 39,
	),
	"Scrubbers pipes" = list(
		"Pipe" = 31,
		"Bent Pipe" = 32,
		"Manifold" = 34,
		"Pipe Cap" = 42,
		"4-Way Manifold" = 36,
		"Upward Pipe" = 38,
		"Downward Pipe" = 40,
	),
	"Fuel pipes" = list(
		"Pipe" = 45,
		"Bent Pipe" = 46,
		"Manifold" = 47,
		"Pipe Cap" = 51,
		"4-Way Manifold" = 48,
		"Upward Pipe" = 49,
		"Downward Pipe" = 50,
	),
	"Devices" = list(
		"Universal Pipe Adapter" = 28,
		"Connector" = 4,
		"Unary Vent" = 7,
		"Gas Pump" = 10,
		"Pressure Regulator" = 15,
		"High Power Gas Pump" = 16,
		"Scrubber" = 11,
		"Meter" = 1,
		"Gas Filter" = 13,
		"Gas Filter - Mirrored" = 25,
		"Gas Mixer - T" = 24,
		"Omni Gas Mixer" = 26,
		"Omni Gas Filter" = 27,
	),
	"Heat Exchange" = list(
		"Pipe" = 2,
		"Bent Pipe" = 3,
		"Junction" = 6,
		"Heat Exchanger" = 17,
		"Wall Radiator" = 54,
		"Junction Left" = 52,
		"Junction Right" = 53,
	),
	"Disposal Pipes" = list(
		"Pipe" = 0,
		"Bent Pipe" = 1,
		"Junction" = 2,
		"Y-Junction" = 4,
		"Trunk" = 5,
		"Bin" = 6,
		"Outlet" = 7,
		"Chute" = 8,
		"Upwards" = 13,
		"Downwards" = 14,
		"Sorting" = 9,
		"Sorting (Wildcard)" = 9,
		"Tagger" = 11,
		"Tagger (Partial)" = 12,
		"Diversion" = 13,
		"Diversion Switch" = 14,
		"Disposal Switch" = 15
	),
))
