/obj/item/organ_module
	name = "embedded organ module"
	desc = "A mechanical augment designed for implantation into a human's flesh or prosthetics."
	icon = 'icons/obj/implants.dmi'
	matter = list(MATERIAL_STEEL = 12)
	var/augment_size = ITEM_SIZE_TINY
	w_class = ITEM_SIZE_TINY
	/// List of organ tags
	var/list/allowed_organs = list()
	/// For cybernetic-specific applicator sprite calls.
	var/mod_overlay
	/// Movspeed modifier added to organ's overall tally.
	var/organ_tally = 0

	var/toggled = FALSE
	/// Action button name used when implanted (not when held).
	var/implant_action_name = null

	var/module_flags = OM_FLAG_SCANNABLE | OM_FLAG_MECHANICAL // Can be replaced with OM_FLAG_DEFAULT

	/// If not null (see defines), will prevent installing more than one module of the same type into one prosthesis.
	var/module_type = null

	var/cooldown = (0.5 SECONDS)

	/// CPU power generated by this augment.
	var/cpu_power = 0
	/// CPU power consumed by this augment
	var/cpu_load = 0

	/// The number of loadout points for selecting this module in char setup.
	var/loadout_cost = 0
	/// The number of augmentation points for selecting this module in char setup.
	var/augment_cost = 0
	/// Whether this module can be selected in character setup menu
	var/available_in_charsetup = TRUE
	var/list/allowed_jobs
	var/list/allowed_roles

/obj/item/organ_module/Initialize()
	. = ..()
	if(action_button_name)
		implant_action_name = action_button_name
		action_button_name = null

/obj/item/organ_module/Destroy()
	if(istype(loc, /obj/item/organ))
		remove(loc)
	return ..()


/obj/item/organ_module/proc/install(obj/item/organ/E)
	if(!E)
		return     /// le costil, must fix runtimes
	E.implants |= src
	E.organ_modules |= src
	E.occupied_space += augment_size
	forceMove(E)
	_on_install(E)
	post_install(E)

/obj/item/organ_module/proc/has_duplicate_in(obj/item/organ/E)
	for(var/obj/item/organ_module/module in E.organ_modules)
		if(module == src)
			continue
		if(istype(module, src.type))
			return TRUE
	return FALSE

/obj/item/organ_module/proc/can_install_in(obj/item/organ/affected, mob/user)
	if(!affected)
		return FALSE
	if(!(affected.organ_tag in allowed_organs))
		if(user)
			to_chat(user, SPAN_WARNING("You can't install [name] in the [affected.name]."))
		return FALSE
	if(has_duplicate_in(affected))
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install another [name] into the [affected]."))
		return FALSE
	if(BP_IS_ROBOTIC(affected) && !(module_flags & OM_FLAG_MECHANICAL))
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install the [src] into the [affected]."))
		return FALSE
	if(!BP_IS_ROBOTIC(affected) && !(module_flags & OM_FLAG_BIOLOGICAL))
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install the [src] into the [affected]."))
		return FALSE
	if(module_type == OM_TYPE_PROCESSOR && affected.organ_tag != BP_HEAD)
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install the [src] into the [affected]."))
		return FALSE
	if(module_type == OM_TYPE_ACTUATOR && (affected.organ_tag == BP_HEAD || BP_IS_ROBOTIC(affected)))
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install the [src] into the [affected]."))
		return FALSE
	if((augment_size + affected.occupied_space) > affected.max_module_size)
		if(user)
			to_chat(user, SPAN_NOTICE("You cannot install the [src] into the [affected]."))
		return FALSE
	return TRUE

/obj/item/organ_module/proc/_on_install(obj/item/organ/E)
	if(organ_tally)
		var/obj/item/organ/external/ex = E
		ex?.update_tally()

/// Called after module is installed. Override for custom behavior.
/obj/item/organ_module/proc/post_install(obj/item/organ/E)
	SHOULD_CALL_PARENT(FALSE)
	return

/obj/item/organ_module/proc/remove(obj/item/organ/E)
	_on_remove(E)

	E.implants -= src
	E.organ_modules -= src
	E.occupied_space = max(0, E.occupied_space - augment_size)

	if(!QDELETED(src))
		forceMove(E.drop_location())

	post_removed(E)

/obj/item/organ_module/proc/_on_remove(obj/item/organ/E)
	if(organ_tally)
		var/obj/item/organ/external/ex = E
		ex?.update_tally()

/// Called after module is removed. Override for custom behavior.
/obj/item/organ_module/proc/post_removed(obj/item/organ/E)
	SHOULD_CALL_PARENT(FALSE)
	return

/obj/item/organ_module/proc/organ_removed()
	return

/obj/item/organ_module/proc/organ_installed()
	return

/obj/item/organ_module/proc/is_allowed_for_job(datum/job/job)
	if(!job)
		return TRUE
	var/list/roles = allowed_roles
	if(!length(roles))
		roles = allowed_jobs
	if(!length(roles))
		return TRUE
	return (job.type in roles)
