$ftlFile = $args[0]

if ($null -eq $ftlFile) {
    Write-Host 'Pass as the first argument path to a .ftl file'
    exit
}

if ((Test-Path $ftlFile) -eq $false) {
    Write-Host 'File does not exist'
    exit
}

$definePrefix = 'L10N_'
$targetFile = 'code/__defines/l10n.dm'

$output = "// THIS FILE IS AUTO GENERATED BY GenDefines.ps1`n"

foreach ($line in Get-Content $ftlFile) {
    if ($line -match '^#.*') {
        $output += ("`n// " + $line.Replace('#', '').Trim() + "`n`n")
    }
    elseif ($line -match '^.*=') {
        $var = $line.Split(' ')[0]
        $output += "#define $definePrefix" + $var.ToUpper().Replace('-', '_') + " `"$var`"`n"
    }
}

$output.Trim() | Out-File -FilePath $targetFile
