name: Check Merge Conflicts

on:
  push:
    branches:
      - dev
  pull_request_target:

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: ike709/actions-label-merge-conflict@9eefdd17e10566023c46d2dc6dc04fcb8ec76142
        with:
          dirtyLabel: "⚠️ конфликты"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
